version: "3"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./docker_files/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/
    ports:
      - "80:80"
    networks:
      - web
    depends_on:
      - php

  php:
    build:
      context: ./
      args:
        user: vlad
        uid: 1000
      dockerfile: docker_files/php/Dockerfile
    volumes:
      - ./:/var/www/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - web

  database:
    image: mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
    networks:
      - web


networks:
  web:
    driver: bridge

volumes:
  database:
    driver: local
